In [6]:
# l1=[2,3,4]
# l2=[4,5,6]
# l=[]
# for i in range(0,len(l1)):
#     print(l1[i]*l2[i])
# #     l.append(l1[i]*l2[i])
# # print(l)

8
15
24


In [10]:
import numpy as np
arr=np.array([23,45,67,66])
print(arr,type(arr))

ModuleNotFoundError: No module named 'numpy'

In [8]:
pip install numpy

     |████████████████████████████████| 17.3 MB 7.0 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),id(arr),arr.ndim)

[1 2 3 4 5] <class 'numpy.ndarray'> 140201776587760 1


In [5]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr,arr.ndim)

[[[[[1 2 3 4 5]]]]] 5


In [6]:
print(np.__version__)


1.24.4


In [7]:
arr=np.array([12,34,4,667,56])
print(arr,type(arr))

[ 12  34   4 667  56] <class 'numpy.ndarray'>


In [11]:
arr=np.array(34)
print(arr,type(arr),arr.ndim,id(arr))

34 <class 'numpy.ndarray'> 0 140201776589680


In [15]:
arr=np.array([34,56,78,89,345])
print(arr,type(arr),id(arr),arr.ndim)

[ 34  56  78  89 345] <class 'numpy.ndarray'> 140201776296368 1


In [17]:
arr=np.array([[[1,2,3],[23,45,67]]])
print(arr,type(arr),id(arr),arr.ndim)

[[[ 1  2  3]
  [23 45 67]]] <class 'numpy.ndarray'> 140201776298480 3


In [23]:
arr=np.array([1,23,45])
print(arr[1]+arr[-1])

68


In [27]:
arr=np.array([[1,2,3],[34,56,78]])
print(arr[0,1])

2


In [31]:
arr=np.array([[[1,2,3],[4,5,6],[9,8,7]]])
print(arr[0,0,1]*arr[0,1,-1])

12


In [34]:
arr=np.array([[[1,2,3],[34,56,78],[54,7,6]]])
print(arr[0,1,-1])

78


In [37]:
arr=np.array([1,23,45])
print(arr[::-1])

[45 23  1]


In [52]:
arr=np.array([[1,2,3],[34,56,78]])
print(arr[0,1:])
print(arr[1,-1])

[2 3]
78


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::-1])

[7 6 5 4 3 2 1]


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:-1:2])

[2 4 6]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [62]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0]+arr[1])
print(arr[0,1:])

[ 7  9 11 13 15]
[2 3 4 5]


In [64]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


In [69]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,2:],arr.dtype)

[ 8  9 10] int64


In [70]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [73]:
arr=np.array([1,2,3,4],dtype='i4')
print(arr,arr.dtype,arr.ndim)

[1 2 3 4] int32 1


In [77]:
arr = np.array(['a', '2', '3'], dtype='U') 
print(arr)

['a' '2' '3']


In [89]:
arr = np.array([1.1, 2.1, 3.1])
newarr=arr.astype(int)
print(newarr)

[1 2 3]


In [91]:
arr = np.array([1, 0, 3])
newarr=arr.astype(bool)
print(newarr,newarr.dtype)

[ True False  True] bool


In [92]:
arr=np.array([23,45,67,656])
v=arr.copy()
arr[0]=3434
print(v,arr)

[ 23  45  67 656] [3434   45   67  656]


In [93]:
arr=np.array([1,2,3,4,5,6])
x=arr.view()
x[0]=34
print(arr,x)

[34  2  3  4  5  6] [34  2  3  4  5  6]


In [98]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape,arr.ndim)

(2, 4) 2


In [99]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]],ndmin=5)
print(arr,arr.shape)

[[[[[1 2 3 4]
    [5 6 7 8]]]]] (1, 1, 1, 2, 4)


In [101]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [105]:
arr = np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [106]:
arr=np.array([1,2,3,34])
for i in arr:
    print(i)

1
2
3
34


In [109]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [111]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in np.nditer(arr):
    print(i,type(i))

1 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>
5 <class 'numpy.ndarray'>
6 <class 'numpy.ndarray'>
7 <class 'numpy.ndarray'>
8 <class 'numpy.ndarray'>


In [122]:
arr = np.array([1, 2, 3])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['U']):
    print(i)

1
2
3


In [124]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in np.nditer(arr[:,::2]):
    print(i)

1
3
5
7


In [128]:
arr = np.array([[1, 2, 3],[6,7,8]])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 6
(1, 1) 7
(1, 2) 8


In [133]:
arr=np.array([1,2,3])
arr1=np.array([56,7,6])
ar=np.concatenate((arr,arr1))
print(ar)

[ 1  2  3 56  7  6]


In [136]:
arr=np.array([[[1,2,3],[4,5,6],[34,56,78]]])
print(arr[0,0,0]+arr[0,1,0])

5


In [139]:
arr=np.array([[1,2],[4,3]])
ar1=np.array([[2,6],[56,7]])
aa=np.concatenate((arr,ar1),axis=1)
print(aa)

[[ 1  2  2  6]
 [ 4  3 56  7]]


In [149]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [150]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [152]:
arr = np.array([34,56,8,4,67,45,78,3])
newarr=np.array_split(arr,4)
print(newarr)

[array([34, 56]), array([8, 4]), array([67, 45]), array([78,  3])]


In [153]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [154]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [155]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [159]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [164]:
arr=np.array([1,2,3,5,2,4,2,5,2,56])
v=np.where(arr%2==0)
print(v)

(array([1, 4, 5, 6, 8, 9]),)


In [166]:
arr=np.array([1,2,3,5,2,4,2,5,2,56])
a=np.where(arr%2==0)
print(a)

(array([1, 4, 5, 6, 8, 9]),)


In [171]:
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,9)
print(x)

3


In [172]:
arr = np.array([1, 3, 5, 7])
x=np.searchsorted(arr,3)
print(x)

1


In [173]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
v=np.sort(arr)
print(v)

[[2 3 4]
 [0 1 5]]


In [175]:
arr = np.array([41, 42, 43, 44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [177]:
arr=np.array([41,42,43,44])
lst=[]
for i in arr:
    if i>42:
        lst.append(True)
    else:
        lst.append(False)
newarr=arr[lst]
print(newarr)

print(lst)

[43 44]
[False, False, True, True]


In [178]:
arr = np.array([41, 42, 43, 44])
filter_arr=arr>42
newar=arr[filter_arr]
print(filter_arr)
print(newar)

[False False  True  True]
[43 44]


In [179]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
lst=arr%2==0
ac=arr[lst]
print(ac,lst)

[2 4 6] [False  True False  True False  True False]


In [194]:
from numpy import random
x=random.randint(10,30,5)
print(x)

[26 23 17 22 21]


In [200]:
x=random.rand(1,4,3)
print(x)

[[[0.49776715 0.17058961 0.93042375]
  [0.81099014 0.37882178 0.9311386 ]
  [0.79920246 0.77840237 0.46142011]
  [0.52934651 0.9762183  0.86702632]]]


In [201]:
x=random.randint(100,size=5)
print(x)

[69 14 99  4 44]


In [209]:
l=np.array([1,2,3,4,5,6,7,8,9])
v=random.randint(100,size=(2,8))
print(v)

[[49 38 76 66 11 79 62 39]
 [97 30  1 60  7 30 82 38]]


In [212]:
x=random.choice([23,45,67,89])
print(x)

45


In [214]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(10))
print(x)

[5 3 7 5 5 3 3 7 7 7]


In [215]:
# from numpy import random
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[3 1 2 4 5]


In [216]:
arr=np.array([1,2,3,5,6])
print(random.permutation(arr))

[3 6 1 2 5]


In [1]:
import numpy as np

In [7]:
f=np.arange(0,50,5)
s=f.reshape(5,2)
print(s)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]


In [9]:
g=np.linspace(0,5,5)
print(g)

[0.   1.25 2.5  3.75 5.  ]


In [10]:
arr=np.array([[1,2,3],[45,6,78],[22,33,44],[6,78,89]])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [45  6 78]
 [22 33 44]
 [ 6 78 89]]


In [20]:
newarr1=newarr.argmin()
print(newarr1)

0


In [1]:
import numpy as np

In [5]:
var = np.array([1,2,3,4,5])
print(var,var.dtype,var.ndim,var.shape)

[1 2 3 4 5] int64 1 (5,)


In [13]:
a=78
b=45
v=np.subtract(a,b)
print(v)

33


In [1]:
import numpy as np

In [2]:
arr=np.arange(1,10)
v=arr.reshape(3,3)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
c=v.transpose()
print(c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
import random
v=np.random.ranf([10,5])
print(v)

[[0.55923184 0.29187107 0.41379863 0.18639415 0.0939455 ]
 [0.24090713 0.36660223 0.39996415 0.68062381 0.29721169]
 [0.67226535 0.87580708 0.54243621 0.42796934 0.33323647]
 [0.58642313 0.40594645 0.95109415 0.46064284 0.84985445]
 [0.58008797 0.26468004 0.8869594  0.84888944 0.04487839]
 [0.51227347 0.26693331 0.12413084 0.37781279 0.16573121]
 [0.91045234 0.49966281 0.84851192 0.58039492 0.84931126]
 [0.26023151 0.08376534 0.41931488 0.37948224 0.69393722]
 [0.91737581 0.53245388 0.49436194 0.48918563 0.94477305]
 [0.43183197 0.32675086 0.54501498 0.61744591 0.66665919]]


In [19]:
a=np.array([1,2,3,4,5,6])
b=np.array([34,56,78,89,23,45])
v=a+b
v1=a-b
v2=a*b
v3=b//a
v4=b%a
print(v,v1,v2,v3,v4)

[35 58 81 93 28 51] [-33 -54 -75 -85 -18 -39] [ 34 112 234 356 115 270] [34 28 26 22  4  7] [0 0 0 1 3 3]


In [35]:
import random
n=random.randrange(8)
print(n)

7


In [36]:
print(np.__version__)

1.24.4


In [ ]:
arr=np.array([1,2,3,4,5])
prin

In [3]:
import numpy as np
arr=np.array(23,ndmin=5)
print(arr,type(arr),arr.ndim,arr.shape)

[[[[[23]]]]] <class 'numpy.ndarray'> 5 (1, 1, 1, 1, 1)


In [6]:
arr=np.array([23,45,6,89,0,45,45,2,3])
a=arr[2]+arr[-1]
print(a,type(a))

9 <class 'numpy.int64'>


In [9]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[34,56,78,90,34,56]])
v= arr(0,2)


TypeError: 'numpy.ndarray' object is not callable

In [15]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[34,56,78,90,34,56]])
print(arr[1,::-1])

[56 34 90 78 56 34]


In [19]:
arr=np.array([[[1,2,3],[4,5,6],[34,56,78],[90,34,56]]])
print(arr[0,0,1])

2


In [23]:
print(arr[0,1,2],arr[0,2,2])

6 78


In [35]:
a=np.array([12,34,56,78,3,4,8,547,45,7,34],dtype='S')
print(a,type(a))

[b'12' b'34' b'56' b'78' b'3' b'4' b'8' b'547' b'45' b'7' b'34'] <class 'numpy.ndarray'>


In [38]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype,type(arr),arr)

<U6 <class 'numpy.ndarray'> ['apple' 'banana' 'cherry']


In [43]:
arr=np.array([23,45,67,34,6,7,3,7])
v=arr.copy()
arr[-1]=345
print(v,arr)

[23 45 67 34  6  7  3  7] [ 23  45  67  34   6   7   3 345]


In [44]:
arr=np.array([23,45,67,34,6,7,3,7])
v=arr.view()
arr[3]=75657
print(arr,v)

[   23    45    67 75657     6     7     3     7] [   23    45    67 75657     6     7     3     7]


In [45]:
for i in arr:
    print(i)

23
45
67
75657
6
7
3
7


In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [56]:
a=np.array([[1,2,3],[3,4,5],[45,67,88]])
c=np.array([[23,45,67],[33,4,4],[45,67,89]])
vv=np.concatenate((a,c),axis=1)
print(vv)

[[ 1  2  3 23 45 67]
 [ 3  4  5 33  4  4]
 [45 67 88 45 67 89]]


In [65]:
arr=np.array([1,2,3])
arr2=np.array([34,56,78])
a=np.dstack((arr,arr2))
print(a)

[[[ 1 34]
  [ 2 56]
  [ 3 78]]]


In [69]:
a=np.array([23,45,67,34,6,33,12,5,23])
v=np.array_split(a,3,axis=0)
print(vv)

[[ 1  2  3 23 45 67]
 [ 3  4  5 33  4  4]
 [45 67 88 45 67 89]]


In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
nn=np.vsplit(arr,3)
print(nn)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [90]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x=np.searchsorted(arr,[2,4,3])
print(x)

[1 3 2]


In [87]:
arr = np.array([3, 2, 0, 1])

In [88]:
print(arr)

[3 2 0 1]


In [89]:
arr = np.array([3, 2, 0, 1])
v=np.sort(arr)
print(v)

[0 1 2 3]


In [92]:
import random
arr=np.array([23,45,67,45,78])
random.shuffle(arr)
print(arr)

[67 45 23 45 78]


In [94]:
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(random.permutation(arr))

[2 4 1 3 6 5]


In [95]:
import pandas as pd
data={'car':['bmw','volvo','ford'],'passing':[3,7,2]}
vv=pd.dataframe(data)
print(vv)

ModuleNotFoundError: No module named 'pandas'

In [96]:
pip install pandas


     |████████████████████████████████| 12.4 MB 330 kB/s eta 0:00:011
     |████████████████████████████████| 505 kB 457 kB/s eta 0:00:01
     |████████████████████████████████| 345 kB 441 kB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [101]:
import pandas as pd
data={'car':['bmw','volvo','ford'],'passing':[3,7,2]}
vv=pd.DataFrame(data,index=[23,45,67])
print(vv)

      car  passing
23    bmw        3
45  volvo        7
67   ford        2


In [104]:
a=[23,45,67,78,55]
v=pd.Series(a,index=[3,4,5,6,56])
print(v)

3     23
4     45
5     67
6     78
56    55
dtype: int64


In [105]:
calories = {"day1": 420, "day2": 380, "day3": 390}
mv=pd.Series(calories)
print(mv)

day1    420
day2    380
day3    390
dtype: int64


In [106]:
data={'calories':[34,56,68],'duration':[45,67,78]}
mv=pd.DataFrame(data)
print(mv)

   calories  duration
0        34        45
1        56        67
2        68        78


In [107]:
mv

calories  duration
0        34        45
1        56        67
2        68        78

In [111]:
print(mv.loc[1])

calories    56
duration    67
Name: 1, dtype: int64


In [113]:
print(mv.loc[[0,1]])

   calories  duration
0        34        45
1        56        67


In [114]:
mv


calories  duration
0        34        45
1        56        67
2        68        78

In [115]:
print(mv.loc[0])

calories    34
duration    45
Name: 0, dtype: int64
